In [10]:
import pandas as pd

file_path = file_path = r'C:\Users\vaise\OneDrive\Desktop\DI-Bootcamp\week4\Day2\exer.xpW4D2\Datasets\Iris_Dataset\Iris.csv'
iris_data = pd.read_csv(file_path)

iris_data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
from datetime import datetime


daily_fetch = {
    'Currency': ['EUR', 'GBP', 'JPY', 'AUD', 'CAD'],
    'ExchangeRate': [1.06, 0.82, 141.2, 1.46, 1.35], 
    'Date': [datetime(2024, 11, 26)] * 5  
}


df_currency = pd.DataFrame(daily_fetch)


df_currency.to_excel('currency_prices.xlsx', index=False, engine='openpyxl')

df_currency.to_json('currency_prices.json', orient='records', lines=True)


print(df_currency)

  Currency  ExchangeRate       Date
0      EUR          1.06 2024-11-26
1      GBP          0.82 2024-11-26
2      JPY        141.20 2024-11-26
3      AUD          1.46 2024-11-26
4      CAD          1.35 2024-11-26

In [22]:
import pandas as pd 

file_path = r'C:\Users\vaise\OneDrive\Desktop\DI-Bootcamp\week4\Day3\exercise_XPW4D3\posts.json'
json_posts = pd.read_json(file_path)
json_posts.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

Question 4-6