In [3]:
import pandas as pd

data = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}

df = pd.DataFrame(data)

In [4]:
df.head()

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

In [5]:
df[['Price', 'Copies Sold']].describe()

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Book Title   5 non-null      object
 1   Author       5 non-null      object
 2   Genre        5 non-null      object
 3   Price        5 non-null      float64
 4   Copies Sold  5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 328.0+ bytes

In [8]:
sorted_by_price = df.sort_values(by='Price', ascending=True)

In [ ]:
sorted_by_price.